export * from './Themes/Themes';
export * from './DropMenu/DropMenu';
export * from './Search/Search';
export * from './Movie/Movie';
export * from './Movies/Movies';
export * from './SearchByGenre/SearchByGenre';
export * from './Header/Header';
export * from './MovieCard/MovieCard';
export * from './StarRating/StarRating';
